#!/bin/bash

mkdir -p output

rm output/*.o 2> /dev/null
mv -f output/test.nes output/test.nes.old 2> /dev/null

# First, assemble main source file to an object file:
ca65 test.s -o output/test.o -l

# Then, link the object file into a binary, generating map.txt too.
# By using "-t none" we get a plain conversion to a binary file with no smarts.
ld65 output/test.o -m output/map.txt -o output/test.nes -C nesfile.ini

if [ "$1" == "-d" ]; then
	hexdump -C output/test.nes
fi

# Show what we made:
ls -ald output/*.nes

